### ISSUE TITLE
Redirect https://glideservers.com to https://www.glideservers.com with .htaccess

### ISSUE THREAD

**Issue by JamesKingdom** [GlideServers/Glideservers-website#58]
We can add this to the .htaccess
```
23 | RewriteEngine OnRewriteCond %{HTTP_HOST} ^glideservers.com [NC]RewriteRule ^(.*)$ https://www.glideservers.com/$1 [L,R=301]
```

@logichub Do we need `{HTTPS_HOST}`` or will `{HTTP_HOST}` work?

**Comment by logichub** [comment]
@JamesKingdom If you are on Apache, then you can do it via .htaccess file too.

**Comment by logichub** [comment]
@JamesKingdom I have made changes in the `.htaccess` file too. See here
https://github.com/GlideServers/Glideservers-website/pull/78/commits/e5e39381569c4009467237f47f1a5cc5fd5be163

This is the best solution for redirection of non-www to www links whether it has http or https protocol.

**Comment by JamesKingdom** [comment]
This was done in #78
