### ISSUE TITLE
Change Navbar icons

### ISSUE THREAD

**Issue by JamesKingdom** [GlideServers/Glideservers-website#69]
We can change the navbar icons to something better - here's the code
https://github.com/GlideServers/Glideservers-website/blob/34e8268798e7a7d27b7689d1fee4f7acc8221506/includes/topnav.html#L6-L8

- [ ] Change `Client Area ` to `fa fa-gbp`
- [ ] Change `Control Panel ` to `fa fa-server`

**Comment by logichub** [comment]
Why not `fa-user` for Client and `fa-sliders` for Control Panel?

![image](https://user-images.githubusercontent.com/6245858/31531405-61df4918-b000-11e7-83ad-00af826c39d8.png)

**Comment by JamesKingdom** [comment]
> @logichub
  Why not fa-user for Client and fa-sliders for Control Panel?

This would be great, will accept a PR if you want to change them
