### ISSUE TITLE
Fix broken JS link

### ISSUE THREAD

**Issue by JamesKingdom** [GlideServers/Glideservers-website#91]
We need to change https://github.com/GlideServers/Glideservers-website/blob/72939a53c9e3d404f4a94e7cc523957230b25142/ssd-vps.html#L86 to
`ripple-effect.min.js`

**Comment by Yoshyyy** [comment]
I'll take this?

**Comment by JamesKingdom** [comment]
@Yoshyyy Sorry, this was already done.
